### ISSUE TITLE
atf presenter with pyplot

### ISSUE THREAD

**Issue by floweisshardt** [mojin-robotics/atf#11]
details see https://github.com/floweisshardt/atf/issues/108
fixes https://github.com/floweisshardt/atf/issues/108

**Comment by Acuda** [comment]
i pushed a snapshot of the first raw version https://github.com/Acuda/atf/tree/feature/atf_plotter. there are still hardlinks in the code, so i had not made a pullrequest yet. 

for the plots self i need input how the data is represented (plot-type https://matplotlib.org/gallery/index.html, grouping, colors, etc.) in a useful way. not used yet, but for some data i think this kind of chart could be useful https://matplotlib.org/gallery/statistics/boxplot_demo.html#sphx-glr-gallery-statistics-boxplot-demo-py

examples (just for impressions of the under laying data) of the first 3 points from https://github.com/floweisshardt/atf/issues/108 as simple and unlabeled bar-charts following.

> * visualize data and groundtruth for a given metric in a given testblock for a given test, e.g. `time` in `testblock_small` from `atf_test/ts0_c0_r0_e0_s0_0`

![figure_1-8](https://user-images.githubusercontent.com/4059009/73352724-054fdd80-4292-11ea-970d-cfea8597c074.png)

> * visualize data for a all metrics in a given testblock for a given test

![figure_1-9](https://user-images.githubusercontent.com/4059009/73352733-0bde5500-4292-11ea-8cb0-5e34da270ee2.png)

> * visualize data for all metrics in all testblocks in all tests

![figure_1-10](https://user-images.githubusercontent.com/4059009/73352745-113b9f80-4292-11ea-93d5-e04b923341b9.png)
![figure_1-11](https://user-images.githubusercontent.com/4059009/73353278-4ac0da80-4293-11ea-99d2-a333f4595e06.png)

**Comment by floweisshardt** [comment]
maybe the visualization of the old presenter gives some inspiration:
![image](https://user-images.githubusercontent.com/158051/73361317-076f6780-42a5-11ea-8133-1f6900a9a0b4.png)

![image](https://user-images.githubusercontent.com/158051/73361453-43a2c800-42a5-11ea-9d91-a6c15749c8a1.png)

![image](https://user-images.githubusercontent.com/158051/73361459-47364f00-42a5-11ea-8b2c-de212dbd8943.png)

![image](https://user-images.githubusercontent.com/158051/73361474-4d2c3000-42a5-11ea-9d76-efd51df08f40.png)

**Comment by floweisshardt** [comment]
this might be a good visualization for groundtruth, min/max, average etc
![image](https://user-images.githubusercontent.com/158051/73361621-91b7cb80-42a5-11ea-933b-64c360bfeb71.png)

**Comment by floweisshardt** [comment]
I also like https://matplotlib.org/gallery/statistics/boxplot_color.html#sphx-glr-gallery-statistics-boxplot-color-py

![image](https://user-images.githubusercontent.com/158051/73361792-f4a96280-42a5-11ea-942f-0001cfa9e450.png)

and https://matplotlib.org/gallery/statistics/boxplot_vs_violin.html#sphx-glr-gallery-statistics-boxplot-vs-violin-py

![image](https://user-images.githubusercontent.com/158051/73361771-e9563700-42a5-11ea-8d9d-9c3ca8c31657.png)

**Comment by Acuda** [comment]
in the old way, the each bar is labeld with its corresponding testblock. as mentioned before this will make the bars unrelated to the data if there are more then one kind of metric type in a testblock (e.g. multiple times measured, or multiple tf-translation lookups to different reference frames). i have no idea how to represent metric-variants (each one is an own list entry for the testblock) in a way to get a correlation to the underlying data.

apart from that i also prefer box plots. where the box itself could be the deviation and the thin lines the valid groundtrouth.  violin plots are a little different due to the fact they need a data sample and the data distribution is calculated by the "plot" itself. but we could test the chart-type for aggregated data.

**Comment by Acuda** [comment]
just as impression

> * visualize aggregated data for all test repetitions for a given test, e.g. `atf_test/ts0_c0_r0_e0_s0_0..10`

![figure_1-12](https://user-images.githubusercontent.com/4059009/73765944-98e34b80-4775-11ea-83c1-aa3372b80815.png)
![figure_1-13](https://user-images.githubusercontent.com/4059009/73765946-997be200-4775-11ea-8cd8-c529ffd8e3bb.png)

**Comment by floweisshardt** [comment]
looks good. Here's an `atf_result.txt` from a navigation test: https://gist.github.com/floweisshardt/ef0351bb49a5bac6c531012b66122205. Can you plot that too?

Please open a WIP PR so that we can start playing around with different atf test results.

**Comment by floweisshardt** [comment]
WIP PR is open: https://github.com/floweisshardt/atf/pull/125

**Comment by floweisshardt** [comment]
@Acuda the `atf_results.txt` with data series is to big for gist.github. It's on titan at smb://10.0.1.13/public/Austausch/fmw/ATF/atf_test_app_navigation/results_txt

**Comment by Acuda** [comment]
cli is now available so everyone could (theoretically) plot the graphs on it's own

example: 
```rosrun atf_plotter plot.py plot-metric -m tf_length_translation -tb testblock_small -t ts0_c0_r0_e0_s0_0 ~/atf_result.txt```

and to get info's about the file itself `rosrun atf_plotter plot.py info-structure ~/atf_result.txt` could be helpful

and dont forget there is a help-text about the cli `rosrun atf_plotter plot.py --help`

**Comment by fmessmer** [comment]
https://github.com/floweisshardt/atf/issues/108 is closed - thus closing this issue, too
@floweisshardt should decide when to (finally) merge https://github.com/mojin-robotics/atf/pull/14 to make this feature available on the mojin fork
