### ISSUE TITLE
reduce rostest output but print result summary

### ISSUE THREAD

**Issue by floweisshardt** [mojin-robotics/atf#12]
copy for https://github.com/floweisshardt/atf/issues/122. comment directly in https://github.com/floweisshardt/atf/issues/122

see https://github.com/mojin-robotics/mojin_atf/pull/6

**Comment by fmessmer** [comment]
I guess for now this works for mojin....the issue is still tracked in https://github.com/floweisshardt/atf/issues/122 - no need for duplication as we are using floweisshardt/atf now anyway
